@startuml
skinparam actorStyle awesome
left to right direction
skinparam package {
    BackgroundColor White
    BorderColor #2C3E50
}
skinparam usecase {
    BackgroundColor #EBF5FB
    BorderColor #2E86C1
    ArrowColor #2E86C1
}
actor "Administrateur" as A
actor "Formateur" as F
actor "Étudiant" as E
package "SoliQuiz - Sprint 2 (Avancé)" {
    usecase "Voir le tableau de bord de suivi global" as UC2_7
    usecase "Configuration API avec SoliLMS" as UC2_8
    usecase "Lier QCM à Session / Objectif" as UC2_1
    usecase "Calculer score par objectif" as UC2_2
    usecase "Accéder au feedback détaillé\net correction" as UC2_3
    usecase "Consulter l'historique et\ntableau de bord de progression" as UC2_4
    usecase "Gérer le Timer et sauvegarde\nautomatique (Passation)" as UC2_5
    usecase "Exporter les notes vers SoliLMS" as UC2_6
}
A -- UC2_7
A -- UC2_8
F -- UC2_1
F -- UC2_4
F -- UC2_6
E -- UC2_3
E -- UC2_4
E -- UC2_5
UC2_5 ..> UC2_1 : <<extend>>
UC2_5 ..> UC2_2 : <<include>>
UC2_4 ..> UC2_3 : <<extend>>
UC2_6 ..> UC2_4 : <<extend>>
@enduml