@startuml
skinparam actorStyle awesome
left to right direction
skinparam package {
    BackgroundColor White
    BorderColor #2C3E50
}
skinparam usecase {
    BackgroundColor #EBF5FB
    BorderColor #2E86C1
    ArrowColor #2E86C1
}
actor "Administrateur" as A
actor "Formateur" as F
actor "Étudiant" as E
package "SoliQuiz System" {
    usecase "Gérer les utilisateurs (Rôles)" as UC9
    usecase "Voir le tableau de bord global" as UC10
    usecase "Configuration API SoliLMS" as UC11
    usecase "Gérer les QCM (CRUD)" as UC1
    usecase "Gérer les Questions et Choix" as UC2
    usecase "Lier QCM à une Session/Objectif" as UC3
    usecase "Réaliser une évaluation (Passer QCM)" as UC4
    usecase "Calculer automatiquement les scores" as UC6
    usecase "Consulter les résultats (Total & Objectif)" as UC5
    usecase "Consulter l'historique des évaluations" as UC7
    usecase "Accéder au feedback détaillé/correction" as UC8
}
A -- UC9
A -- UC10
A -- UC11
F -- UC1
F -- UC2
F -- UC3
F -- UC5
E -- UC4
E -- UC5
E -- UC7
E -- UC8
UC1 ..> UC2 : <<include>>
UC3 ..> UC1 : <<extend>>
UC4 ..> UC6 : <<include>>
UC5 ..> UC8 : <<extend>>
UC7 ..> UC5 : <<include>>
@enduml